// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: usermessage.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name holds the identifier of the MSP
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// ipk represents the (serialized) issuer public key
	Ipk []byte `protobuf:"bytes,2,opt,name=ipk,proto3" json:"ipk,omitempty"`
	// user may contain crypto material to configure a default signer
	User *UserMessageConfig `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	// revocation_pk is the public key used for revocation of credentials
	RevocationPk []byte `protobuf:"bytes,4,opt,name=revocation_pk,json=revocationPk,proto3" json:"revocation_pk,omitempty"`
	// epoch represents the current epoch (time interval) used for revocation
	Epoch int64 `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// curve_id indicates which Elliptic Curve should be used
	CurveId string `protobuf:"bytes,6,opt,name=curve_id,json=curveId,proto3" json:"curve_id,omitempty"`
}

func (x *UserConfig) Reset() {
	*x = UserConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConfig) ProtoMessage() {}

func (x *UserConfig) ProtoReflect() protoreflect.Message {
	mi := &file_usermessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConfig.ProtoReflect.Descriptor instead.
func (*UserConfig) Descriptor() ([]byte, []int) {
	return file_usermessage_proto_rawDescGZIP(), []int{0}
}

func (x *UserConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserConfig) GetIpk() []byte {
	if x != nil {
		return x.Ipk
	}
	return nil
}

func (x *UserConfig) GetUser() *UserMessageConfig {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserConfig) GetRevocationPk() []byte {
	if x != nil {
		return x.RevocationPk
	}
	return nil
}

func (x *UserConfig) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *UserConfig) GetCurveId() string {
	if x != nil {
		return x.CurveId
	}
	return ""
}

// UserMessageConfig contains the credential material to set up an identity
type UserMessageConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// cred represents the serialized idemix credential of the default signer
	Cred []byte `protobuf:"bytes,1,opt,name=cred,proto3" json:"cred,omitempty"`
	// sk is the secret key of the default signer, corresponding to credential Cred
	Sk []byte `protobuf:"bytes,2,opt,name=sk,proto3" json:"sk,omitempty"`
	// organizational_unit_identifier defines the organizational unit the default signer is in
	OrganizationalUnitIdentifier string `protobuf:"bytes,3,opt,name=organizational_unit_identifier,json=organizationalUnitIdentifier,proto3" json:"organizational_unit_identifier,omitempty"`
	// role defines whether the default signer is admin, peer, member or client
	Role int32 `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	// enrollment_id contains the enrollment id of this signer
	EnrollmentId string `protobuf:"bytes,5,opt,name=enrollment_id,json=enrollmentId,proto3" json:"enrollment_id,omitempty"`
	// credential_revocation_information contains a serialized CredentialRevocationInformation
	CredentialRevocationInformation []byte `protobuf:"bytes,6,opt,name=credential_revocation_information,json=credentialRevocationInformation,proto3" json:"credential_revocation_information,omitempty"`
	// RevocationHandle is the handle used to single out this credential and determine its revocation status
	RevocationHandle string `protobuf:"bytes,7,opt,name=revocation_handle,json=revocationHandle,proto3" json:"revocation_handle,omitempty"`
}

func (x *UserMessageConfig) Reset() {
	*x = UserMessageConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMessageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessageConfig) ProtoMessage() {}

func (x *UserMessageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_usermessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessageConfig.ProtoReflect.Descriptor instead.
func (*UserMessageConfig) Descriptor() ([]byte, []int) {
	return file_usermessage_proto_rawDescGZIP(), []int{1}
}

func (x *UserMessageConfig) GetCred() []byte {
	if x != nil {
		return x.Cred
	}
	return nil
}

func (x *UserMessageConfig) GetSk() []byte {
	if x != nil {
		return x.Sk
	}
	return nil
}

func (x *UserMessageConfig) GetOrganizationalUnitIdentifier() string {
	if x != nil {
		return x.OrganizationalUnitIdentifier
	}
	return ""
}

func (x *UserMessageConfig) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *UserMessageConfig) GetEnrollmentId() string {
	if x != nil {
		return x.EnrollmentId
	}
	return ""
}

func (x *UserMessageConfig) GetCredentialRevocationInformation() []byte {
	if x != nil {
		return x.CredentialRevocationInformation
	}
	return nil
}

func (x *UserMessageConfig) GetRevocationHandle() string {
	if x != nil {
		return x.RevocationHandle
	}
	return ""
}

type UserPrimaryCred struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrimaryCred []byte `protobuf:"bytes,1,opt,name=primary_cred,json=primaryCred,proto3" json:"primary_cred,omitempty"`
	PrimaryCri  []byte `protobuf:"bytes,2,opt,name=primary_cri,json=primaryCri,proto3" json:"primary_cri,omitempty"`
}

func (x *UserPrimaryCred) Reset() {
	*x = UserPrimaryCred{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPrimaryCred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPrimaryCred) ProtoMessage() {}

func (x *UserPrimaryCred) ProtoReflect() protoreflect.Message {
	mi := &file_usermessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPrimaryCred.ProtoReflect.Descriptor instead.
func (*UserPrimaryCred) Descriptor() ([]byte, []int) {
	return file_usermessage_proto_rawDescGZIP(), []int{2}
}

func (x *UserPrimaryCred) GetPrimaryCred() []byte {
	if x != nil {
		return x.PrimaryCred
	}
	return nil
}

func (x *UserPrimaryCred) GetPrimaryCri() []byte {
	if x != nil {
		return x.PrimaryCri
	}
	return nil
}

type UserDeriveCred struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeriveCred []byte `protobuf:"bytes,1,opt,name=derive_cred,json=deriveCred,proto3" json:"derive_cred,omitempty"`
	DeriveCri  []byte `protobuf:"bytes,2,opt,name=derive_cri,json=deriveCri,proto3" json:"derive_cri,omitempty"`
}

func (x *UserDeriveCred) Reset() {
	*x = UserDeriveCred{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDeriveCred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeriveCred) ProtoMessage() {}

func (x *UserDeriveCred) ProtoReflect() protoreflect.Message {
	mi := &file_usermessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeriveCred.ProtoReflect.Descriptor instead.
func (*UserDeriveCred) Descriptor() ([]byte, []int) {
	return file_usermessage_proto_rawDescGZIP(), []int{3}
}

func (x *UserDeriveCred) GetDeriveCred() []byte {
	if x != nil {
		return x.DeriveCred
	}
	return nil
}

func (x *UserDeriveCred) GetDeriveCri() []byte {
	if x != nil {
		return x.DeriveCri
	}
	return nil
}

type UserAggregateCred struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AggregateCred []byte `protobuf:"bytes,1,opt,name=aggregate_cred,json=aggregateCred,proto3" json:"aggregate_cred,omitempty"`
	AggregateCri  []byte `protobuf:"bytes,2,opt,name=aggregate_cri,json=aggregateCri,proto3" json:"aggregate_cri,omitempty"`
}

func (x *UserAggregateCred) Reset() {
	*x = UserAggregateCred{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAggregateCred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAggregateCred) ProtoMessage() {}

func (x *UserAggregateCred) ProtoReflect() protoreflect.Message {
	mi := &file_usermessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAggregateCred.ProtoReflect.Descriptor instead.
func (*UserAggregateCred) Descriptor() ([]byte, []int) {
	return file_usermessage_proto_rawDescGZIP(), []int{4}
}

func (x *UserAggregateCred) GetAggregateCred() []byte {
	if x != nil {
		return x.AggregateCred
	}
	return nil
}

func (x *UserAggregateCred) GetAggregateCri() []byte {
	if x != nil {
		return x.AggregateCri
	}
	return nil
}

var File_usermessage_proto protoreflect.FileDescriptor

var file_usermessage_proto_rawDesc = []byte{
	0x0a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0xb5, 0x01, 0x0a, 0x0a, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x70, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x69, 0x70, 0x6b, 0x12, 0x2b,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x72,
	0x65, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x6b, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0c, 0x72, 0x65, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6b,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x76, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x75, 0x72, 0x76, 0x65, 0x49,
	0x64, 0x22, 0xaf, 0x02, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x72, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63, 0x72, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x73,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x73, 0x6b, 0x12, 0x44, 0x0a, 0x1e, 0x6f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x6e,
	0x69, 0x74, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x1c, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x55, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6e,
	0x72, 0x6f, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x4a, 0x0a, 0x21, 0x63, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x76, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x1f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x52, 0x65, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x11, 0x72, 0x65, 0x76, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x72, 0x65, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x22, 0x55, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x69, 0x6d, 0x61,
	0x72, 0x79, 0x43, 0x72, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72,
	0x79, 0x5f, 0x63, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x70, 0x72,
	0x69, 0x6d, 0x61, 0x72, 0x79, 0x43, 0x72, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69,
	0x6d, 0x61, 0x72, 0x79, 0x5f, 0x63, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x43, 0x72, 0x69, 0x22, 0x50, 0x0a, 0x0e, 0x55, 0x73,
	0x65, 0x72, 0x44, 0x65, 0x72, 0x69, 0x76, 0x65, 0x43, 0x72, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x64, 0x65, 0x72, 0x69, 0x76, 0x65, 0x5f, 0x63, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0a, 0x64, 0x65, 0x72, 0x69, 0x76, 0x65, 0x43, 0x72, 0x65, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x64, 0x65, 0x72, 0x69, 0x76, 0x65, 0x5f, 0x63, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x64, 0x65, 0x72, 0x69, 0x76, 0x65, 0x43, 0x72, 0x69, 0x22, 0x5f, 0x0a, 0x11,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x43, 0x72, 0x65,
	0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x63,
	0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x61, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x43, 0x72, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x43, 0x72, 0x69, 0x42, 0x1a, 0x5a,
	0x18, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x3b, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_usermessage_proto_rawDescOnce sync.Once
	file_usermessage_proto_rawDescData = file_usermessage_proto_rawDesc
)

func file_usermessage_proto_rawDescGZIP() []byte {
	file_usermessage_proto_rawDescOnce.Do(func() {
		file_usermessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_usermessage_proto_rawDescData)
	})
	return file_usermessage_proto_rawDescData
}

var file_usermessage_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_usermessage_proto_goTypes = []interface{}{
	(*UserConfig)(nil),        // 0: user.UserConfig
	(*UserMessageConfig)(nil), // 1: user.UserMessageConfig
	(*UserPrimaryCred)(nil),   // 2: user.UserPrimaryCred
	(*UserDeriveCred)(nil),    // 3: user.UserDeriveCred
	(*UserAggregateCred)(nil), // 4: user.UserAggregateCred
}
var file_usermessage_proto_depIdxs = []int32{
	1, // 0: user.UserConfig.user:type_name -> user.UserMessageConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_usermessage_proto_init() }
func file_usermessage_proto_init() {
	if File_usermessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_usermessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usermessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMessageConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usermessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPrimaryCred); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usermessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDeriveCred); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usermessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAggregateCred); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_usermessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_usermessage_proto_goTypes,
		DependencyIndexes: file_usermessage_proto_depIdxs,
		MessageInfos:      file_usermessage_proto_msgTypes,
	}.Build()
	File_usermessage_proto = out.File
	file_usermessage_proto_rawDesc = nil
	file_usermessage_proto_goTypes = nil
	file_usermessage_proto_depIdxs = nil
}
